name: debt
description: Light-weight app to track who owes and who you owe money to.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# Read more about versioning at semver.org.
version: 1.5.4

environment:
    sdk: ">=3.0.0 <4.0.0"

module:
    androidX: true

dependencies:
    flutter:
        sdk: flutter
    shared_preferences: ^2.0.13
    intl: any
    flutter_svg: ^2.0.7
    url_launcher: ^6.0.20
    expressions: ^0.2.3
    currency_formatter: ^2.3.0
    collection: ^1.17.2
    flutter_lints: ^2.0.3
    google_mobile_ads: ^6.0.0
    share_plus: ^7.1.0
    material_symbols_icons: ^4.2668.0

dev_dependencies:
    flutter_test:
        sdk: flutter
    msix: ^3.16.8

# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
    fonts:
        - family: ProductSans
          fonts:
              - asset: fonts/productsans.ttf
              - asset: fonts/productsans_bold.ttf
                weight: 800

        - family: Roboto
          fonts:
              - asset: fonts/Roboto-Regular.ttf
              - asset: fonts/Roboto-Medium.ttf
                weight: 500

    assets:
        - assets/logo.svg
    # The following line ensures that the Material Icons font is
    # included with your application, so that you can use the icons in
    # the material Icons class.
    uses-material-design: true

msix_config:
    display_name: Debt Tracker
    logo_path: C:\Users\rvds9\Documents\Data\Coding\Flutter\debt\windows\runner\resources\app_icon.ico
    # store: true
